# Generated by Django 5.2.4 on 2025-07-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('initial_price', models.PositiveIntegerField(blank=True, null=True)),
                ('currtent_price', models.PositiveIntegerField(null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount in percentage', max_digits=5, null=True)),
                ('product_image', models.ImageField(upload_to='productimages/')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_discounted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='store.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='users.seller')),
            ],
        ),
    ]
