# Generated by Django 5.2.4 on 2025-07-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_product1'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product1',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='Productname',
        ),
    ]
