# Generated by Django 5.2.4 on 2025-07-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product1_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currtent_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
